# Axolotl Configuration for Llama-3 DPO Alignment
# Phase 2: Preference alignment after SFT
# Optimized for 2x H100 80GB

base_model: models_llm/sumerian_llama3_sft  # Start from SFT checkpoint
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer
trust_remote_code: true

# Load configuration
load_in_8bit: false
load_in_4bit: true

# LoRA Configuration (continue from SFT)
adapter: lora
lora_r: 64
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
lora_target_linear: true

# DPO Dataset Configuration
datasets:
  - path: data/final_llm_ready/dpo_pairs.json
    type: chatml.intel
    # Format: {"instruction", "input", "chosen", "rejected"}

# DPO Training
rl: dpo
dpo_beta: 0.1  # KL penalty coefficient

# Sequence Configuration
sequence_len: 512
sample_packing: false  # DPO doesn't use packing
pad_to_sequence_len: true

# Hyperparameters (lower LR for alignment)
num_epochs: 1
micro_batch_size: 2
gradient_accumulation_steps: 32
learning_rate: 5e-5
lr_scheduler: cosine
warmup_ratio: 0.1
weight_decay: 0.01

# Optimizer
optimizer: adamw_torch_fused

# Precision
bf16: true
fp16: false
tf32: true

# Flash Attention
flash_attention: true

# Gradient Checkpointing
gradient_checkpointing: true

# Output
output_dir: models_llm/sumerian_llama3_dpo

# Logging
logging_steps: 5
save_strategy: epoch
save_total_limit: 2

# Wandb
wandb_project: sumerian-translation
wandb_run_id: llama3-dpo

# Misc
seed: 42
strict: false
